<?php

/**
 * @file
 * Collect the titles from a Feed Item node via NYT RSS Feed import and display them in a block.
 */

/**
 * Implements hook_menu()
 */
function nyt_feed_block_menu(){
  $items['admin/config/content/nyt_feed_block'] = array(
    'title' => 'New York Times Feed Block Settings',
    'description' => 'Administer the New York Times Feed Block settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'nyt_feed_block_settings_form',
    ),
    'access arguments' => array(
      'manage new york times feed block settings',
    ),
    'file' => 'nyt_feed_block.admin.inc',
  );
  $items['admin/reports/nyt_feed_block'] = array(
    'title' => 'New York Times Feed Block Posts',
    'description' => 'View all the New York Times Feed imported posts.',
    'page callback' => 'nyt_feed_block_posts',
    'access arguments' => array(
      'view new york times feed block posts',
    ),
    'file' => 'nyt_feed_block.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission()
 */
function nyt_feed_block_permission(){
  $permissions['view new york times feed block posts'] = array(
    'title' => t('View New York Times Feed Block Posts'),
    'description' => t('View all the New York Times Feed imported posts on the main NYT posts page.'),
  );
  $permissions['change rss feed used in new york times feed'] = array(
    'title' => t('Change the RSS feed used in the New York Times Feed'),
    'description' => t('Add new RSS feed to be imported.'),
  );
  $permissions['manage new york time feed block settings'] = array(
    'title' => t('Manage New York Times Feed settings'),
    'description' => t('Allow user to manange the New York Times Feed block settings page.'),
  );
  return $permissions;
}

/**
 * Adds a checkbox to the Feeds Item nodes to allow for the specific feed item to be shown in the New York Times Feed block
 */
function nyt_feed_block_form_node_form_alter(&$form, $form_state, $form_id){
  //dsm($form_id);  // print form ID to messages
  $node = $form['#node'];
  //Perform our check to see if we should be performing an action
  $types = variable_get('nyt_feed_block_types', array());
  //Check if this node type is enabled for the NYT Feeds block
  //and that user has access to the per-node settings
  if ($types[$node->type] && user_access('manage new york times feed block settings')){
    //Add a new fieldset with a checkbox for per-node setting
    $form['nyt_feed_block'] = array(
      '#title' => t('NYT Feed Block'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
    );
    $form['nyt_feed_block']['nyt_feed_block_enabled'] = array(
      '#title' => t('Allow this node to be posted to the NYT block'),
      '#type' => 'checkbox',
      '#default_value' => isset($node->nyt_feed_block_enabled) ? $node->nyt_feed_block_enabled : FALSE,
    );
  }
}

/**
 * Implements hook_node_load().
 */
function nyt_feed_block_node_load($nodes, $types){
  foreach ($nodes as $nid => $node){
    //Add nyt_feed_block data to the node object when it is loaded.
    $node->nyt_feed_block_enabled = nyt_feed_block_get_node_enabled($node->nid)
  }
}

/**
 * Implements hook_node_insert().
 */
function nyt_feed_block_node_insert($node){
  if ($node->nyt_feed_block_enabled){
    //If NYT Feed Block is enabled, store the record
    nyt_feed_block_set_node_enabled($node->nid);
  }
}
