<?php

/**
 * @file
 * Collect the titles from a Feed Item node via NYT RSS Feed import and display them in a block.
 */

/**
 * Implements hook_menu()
 */
function nyt_feed_block_menu(){
  $items['admin/config/content/nyt_feed_block'] = array(
    'title' => 'New York Times Feed Block Settings',
    'description' => 'Administer the New York Times Feed Block settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'nyt_feed_block_settings_form',
    ),
    'access arguments' => array(
      'manage new york times feed block settings',
    ),
    'file' => 'nyt_feed_block.admin.inc',
  );
  $items['admin/reports/nyt_feed_block'] = array(
    'title' => 'New York Times Feed Block Posts',
    'description' => 'View all the New York Times Feed imported posts.',
    'page callback' => 'nyt_feed_block_posts',
    'access arguments' => array(
      'view new york times feed block posts',
    ),
    'file' => 'nyt_feed_block.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission()
 */
function nyt_feed_block_permission(){
  $permissions['view new york times feed block posts'] = array(
    'title' => t('View New York Times Feed Block Posts'),
    'description' => t('View all the New York Times Feed imported posts on the main NYT posts page.'),
  );
  $permissions['change rss feed used in new york times feed'] = array(
    'title' => t('Change the RSS feed used in the New York Times Feed'),
    'description' => t('Add new RSS feed to be imported.'),
  );
  $permissions['manage new york time feed block settings'] = array(
    'title' => t('Manage New York Times Feed settings'),
    'description' => t('Allow user to manange the New York Times Feed block settings page.'),
  );
  return $permissions;
}
